spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huige?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 666
server:
  port: 9000
mybatis:
  mapper-locations: classpath:mapper/*.xml